# Generated by Django 4.2.7 on 2025-06-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessidea',
            name='business_plan',
            field=models.FileField(blank=True, null=True, upload_to='business_plans/'),
        ),
    ]
